spring:
  application:
    name: ratelimiting
  data:
    mongodb:
      database: ratelimit
      host: localhost
      port: 27017
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    root: INFO

ratelimit:
  maxRequest: 5
  ttl : 60

